apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k6-manager.fullname" . }}
  namespace: {{ include "k6-manager.namespace" . }}
  labels:
    {{- include "k6-manager.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k6-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k6-manager.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k6-manager.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: K6_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K6_DEFAULT_RUNNER_IMAGE
              value: {{ .Values.k6.defaultRunnerImage | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
