apiVersion: v1
kind: Service
metadata:
  name: {{ include "k6-manager.fullname" . }}
  namespace: {{ include "k6-manager.namespace" . }}
  labels:
    {{- include "k6-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "k6-manager.selectorLabels" . | nindent 4 }}
